name: ui_aqua_button_flutter
description: "Widget to display MacOS-X Aqua-Style button."
version: 0.0.2+1
home_page: http://www.icodeforyou.com
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.2.5 <4.0.0" # % flutter --version => values of "Dart"
  flutter: ">=3.16.8"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:
